### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by jeroen** [r-windows/checks#5]
The libxml headers are a in a subdir `/include/libxml2` and also `-llzma` is missing. This works:

```r
Sys.setenv(LOCAL_CPPFLAGS = "-I/mingw$(WIN)/include/libxml2")
Sys.setenv(LOCAL_LIBS = '-llzma')
install.packages("XML")
```

**Comment by jeroen** [comment]
NB: I dropped lzma support from libxml, so `-llzma` flag no longer needed.

**Comment by adamrobinson361** [comment]
@jeroen - Note this works with R 3.5.1 but not with 3.4.2. Are you intending backwards compatibility or will rtools40 be for 3.5 forward?

**Comment by grandtiger** [comment]
Looks like Sys.setenv(LOCAL_LIBS = '-llzma') caused problem in the latest version of r-testing with rtool40. The following works fine for me.

```
Sys.setenv(LOCAL_CPPFLAGS = "-I/mingw$(WIN)/include/libxml2")
install.packages("XML")
install.packages("xml2")
```

**Comment by aadler** [comment]
I'm having a problem

```
> Sys.setenv(LOCAL_CPPFLAGS = "-I/mingw$(WIN)/include/libxml2")
> Sys.setenv(LOCAL_LIBS = '-llzma')
> install.packages("XML", type = 'source')
trying URL 'https://cran.rstudio.com/src/contrib/XML_3.98-1.19.tar.gz'
Content type 'application/x-gzip' length 1600788 bytes (1.5 MB)
downloaded 1.5 MB

* installing *source* package 'XML' ...
** package 'XML' successfully unpacked and MD5 sums checked
** using staged installation
** libs
C:/Rtools/mingw_64/bin/gcc  -I"C:/R/RCurrent/R-36~1.0/include" -DNDEBUG -I/include/libxml2 -I/include -D_R_=1 -DUSE_R=1 -DUSE_XML_VERSION_H=1 -DLIBXML -DUSE_EXTERNAL_SUBSET=1 -DROOT_HAS_DTD_NODE=1 -DUMP_WITH_ENCODING=1 -DXML_ELEMENT_ETYPE=1  -DXML_ATTRIBUTE_ATYPE=1 -DLIBXML2=1 -DHAVE_XML_HAS_FEATURE -DLIBXML_STATIC    -I"C:/rtools40/mingw64/include"     -O2 -std=gnu99 -march=native -c DocParse.c -o DocParse.o
In file included from DocParse.c:10:0:
DocParse.h:18:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
compilation terminated.
make: *** [C:/R/RCurrent/R-36~1.0/etc/x64/Makeconf:208: DocParse.o] Error 1
ERROR: compilation failed for package 'XML'
* removing 'C:/R/RCurrent/R-3.6.0/library/XML'
Warning in install.packages :
  installation of package ‘XML’ had non-zero exit status
```

**Comment by jeroen** [comment]
Did you `pacman install mingw-w64-{i686,x86_64}-libxml2` ?

**Comment by aadler** [comment]
Yes.

**Comment by aadler** [comment]
You're correct; this is tied to the issue I had in #40 in that even though I compiled R with rtools40, the package installation was defaulting to RTools 3.5. Sorry

**Comment by Sithara85** [comment]
Hi, 

I am trying to install CytoML. I have installed XML and xml2 as suggested in the thread. I am still getting below error which points to libxml2.a  missing. Can you suggest a solution please?

C:/rtools40/mingw32/bin/g++ -shared -s -static-libgcc -o CytoML.dll tmp.def RcppExports.o parseFlowJoWorkspace.o -LC:/Users/svivek/DOCUME~1/R/R-40~1.2/bin/i386 -lRlapack -LC:/Users/svivek/DOCUME~1/R/R-40~1.2/bin/i386 -lRblas -lgfortran -lm -lquadmath //i386/lib/libxml2.a C:/Users/svivek/Documents/R/R-4.0.2/library/cytolib/lib/i386/libcytolib.a C:/Users/svivek/Documents/R/R-4.0.2/library/RProtoBufLib/lib/i386/libprotobuf-lite.a -LC:/Users/svivek/Documents/R/R-4.0.2/library/RcppParallel/lib/i386 -ltbb -ltbbmalloc -LC:/Users/svivek/DOCUME~1/R/R-40~1.2/library/Rhdf5lib/lib/i386 -lhdf5_cpp -lhdf5 -lcurl -lssh2 -lssl -lcrypto -lwldap32 -lws2_32 -lcrypt32 -lszip -lz -lpsapi -lws2_32 -LC:/Users/svivek/DOCUME~1/R/R-40~1.2/bin/i386 -lR
g++.exe: error: //i386/lib/libxml2.a: No such file or directory
no DLL was created
ERROR: compilation failed for package 'CytoML'

**Comment by aadler** [comment]
@Sithara85, did you call `Sys.setenv(LIB_XML = "$(MINGW_PREFIX)")` before `install.packages("XML", type= "source")` as [suggested here](https://github.com/r-windows/docs/blob/master/packages.md#xml)? I keep on forgetting that step myself.
